name: Testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: mczaplin-gha-runner

    steps:
      - uses: actions/checkout@v4

      - name: Trigger testing
        run: trigger_testing.sh $(git rev-parse HEAD)
