name: BAT Testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  Queued:
    runs-on: mczaplin-gha-runner

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Queue testing
        run: |
          git log -3
          git rev-parse HEAD
          git rev-parse HEAD~1
          git rev-parse HEAD~2
          COMMIT=$(git rev-parse HEAD)
          curl -X POST ${{ secrets.SERVER_URL }} --user ${{ secrets.USER }}:${{ secrets.TOKEN }} --data-urlencode "TARGET_COMMIT=$COMMIT" --data-urlencode "DEBUG=false"
