name: BAT Testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  Queued:
    runs-on: mczaplin-gha-runner

    steps:
      - uses: actions/checkout@v4

      - name: Queue testing
        run: |
          curl -X POST ${{ secrets.SERVER_URL }} --user ${{ secrets.USER }}:${{ secrets.TOKEN }} --data-urlencode "TARGET_COMMIT=${{ github.sha }}" --data-urlencode "DEBUG=false"
