name: BAT Testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: mczaplin-gha-runner

    steps:
      - uses: actions/checkout@v4

      - name: Queue testing
        run: |
          git log -10
          SHA=$(git rev-parse ${{ github.sha }}~1)
          curl -X POST ${{ secrets.SERVER_URL }} --user ${{ secrets.USER }}:${{ secrets.TOKEN }} --data-urlencode "TARGET_COMMIT=$SHA" --data-urlencode "DEBUG=false"
