name: Testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: mczaplin-gha-runner

    steps:
      - uses: actions/checkout@v4

      - name: Trigger testing
        run: curl -X POST ${{ secrets.SERVER_URL }} --user ${{ secrets.USER }}:${{ secrets.TOKEN }} --data-urlencode "TARGET_COMMIT=$(git rev-parse HEAD)" --data-urlencode "DEBUG=false"
