# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Dependancies
        run: | 
          sudo apt update
          sudo apt install -y \
          libasound2-dev \
          libatomic1 \
          libcairo-dev \
          libcurl4-openssl-dev \
          libdrm-dev \
          libdrm-intel1 \
          libdw-dev \
          libelf-dev \
          libgsl-dev \
          libiberty-dev \
          libjson-c-dev \
          libkmod-dev \
          liblzma-dev \
          libncurses-dev \
          liboping-dev \
          libpci-dev \
          libpciaccess-dev \
          libpixman-1-dev \
          libprocps-dev \
          libssl-dev \
          libtool \
          libudev-dev \
          libunwind-dev \
          libxmlrpc-core-c3-dev \
          libxrandr-dev \
          libxv-dev \

      # Runs a single command using the runners shell
      - name: Apply patches
        run: | 
          git config --global user.email "you@example.com"
          git config --global user.name "LGCI"
          ./backport.sh -c base

      - name: Checkout common kconfig
        run: |
          cd kernel
          git clone https://gitlab.freedesktop.org/drm/xe/ci.git .ci
          mkdir -p build64-default
          cp .ci/kernel/kconfig build64-default/.config
          make O=build64-default olddefconfig

      # Runs a set of commands using the runners shell
      - name: Build kernel
        run: |
          cd kernel
          make O=build64-default -j$(nproc)
